In [0]:
!wget https://github.com/git-lfs/git-lfs/releases/download/v2.6.1/git-lfs-linux-amd64-v2.6.1.tar.gz
!tar -xzvf git-lfs-linux-amd64-v2.6.1.tar.gz
!./install.sh
!git lfs install
!git lfs get

--2019-05-21 01:56:42--  https://github.com/git-lfs/git-lfs/releases/download/v2.6.1/git-lfs-linux-amd64-v2.6.1.tar.gz
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github-production-release-asset-2e65be.s3.amazonaws.com/13021798/aa276700-f730-11e8-96fb-bb179337f35f?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIWNJYAX4CSVEH53A%2F20190521%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190521T015642Z&X-Amz-Expires=300&X-Amz-Signature=d5f1a2c855eb87f32b7a82edb8295d77a4f7e70eb57f78482957bf6e32bba6d2&X-Amz-SignedHeaders=host&actor_id=0&response-content-disposition=attachment%3B%20filename%3Dgit-lfs-linux-amd64-v2.6.1.tar.gz&response-content-type=application%2Foctet-stream [following]
--2019-05-21 01:56:42--  https://github-production-release-asset-2e65be.s3.amazonaws.com/13021798/aa276700-f730-11e8-96fb-bb179337f35f?X-Amz-Algorithm=AWS4-HMAC-

In [0]:
import os
# !git clone https://sadikneipp:@github.com/sadikneipp/hack-cambridge4D.git
!git clone https://github.com/sadikneipp/pill-it-up.git
os.chdir('pill-it-up')
!git checkout cloud
!git pull

Cloning into 'pill-it-up'...
remote: Enumerating objects: 307, done.
remote: Counting objects: 100% (307/307), done.
remote: Compressing objects: 100% (307/307), done.
remote: Total 5572 (delta 0), reused 304 (delta 0), pack-reused 5265
Receiving objects: 100% (5572/5572), 238.72 MiB | 11.41 MiB/s, done.
Resolving deltas: 100% (81/81), done.
Checking out files: 100% (3393/3393), done.
Filtering content: 100% (3380/3380), 83.63 MiB | 531.00 KiB/s, done.
Branch 'cloud' set up to track remote branch 'cloud' from 'origin'.
Switched to a new branch 'cloud'
Already up to date.


In [0]:
#torch dependencies
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install torch torchvision 
!pip install Pillow==4.0.0

import torch
print(torch.__version__)

     |████████████████████████████████| 5.6MB 37.0MB/s 
ERROR: torchvision 0.2.2.post3 has requirement pillow>=4.1.1, but you'll have pillow 4.0.0 which is incompatible.
ERROR: scikit-image 0.14.2 has requirement pillow>=4.3.0, but you'll have pillow 4.0.0 which is incompatible.
ERROR: albumentations 0.1.12 has requirement imgaug<0.2.7,>=0.2.5, but you'll have imgaug 0.2.9 which is incompatible.
  Found existing installation: Pillow 4.3.0
    Uninstalling Pillow-4.3.0:
      Successfully uninstalled Pillow-4.3.0


1.1.0


In [0]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import os
from sklearn.metrics import confusion_matrix

os.chdir('model')

In [0]:
import torch
import torchvision
import torchvision.transforms as transforms
from torchvision import datasets, models, transforms
import torchvision.models as models
import torch.optim as optim
from torch.optim import lr_scheduler
from torch.utils.data import random_split
import copy
from torch import nn
import time
import argparse
import pickle
from sklearn.metrics import confusion_matrix
from torch.utils.data import DataLoader

#Environment Parameters
COLAB = True
MODEL_PATH = '../../gdrive/My Drive/demo_diretor/'

BS = 8
WORKERS= 2
N_SPLITS = 1 # number of times to split dataset randomly and fit
SPLIT_MODE = 'auto' #auto will use the torch dataset random splitter, manual will use the premade folder splits
VAL_SIZE = 0.3 #percentage of validation data
N_CLASSES = 5

''' 
Training parameters 

Follows pytorch naming conventions   
'''

LR_0 = 0.01 #initial learning rate
GAMMA = 0.1
N_EPOCHS = 3 #total epochs
STEP_SIZE = 1 #epochs until decay of lr by gamma
MOMENTUM = 0.9
WD = 1e-4 #weight decay

def get_args(): #deprecated for colab e.e
    parser = argparse.ArgumentParser()
    parser.add_argument("-d", "--device", help="pass 'gpu' to turn on GPU")
    args = parser.parse_args()

    return args

def check_create(path):
    if os.path.exists(path):
        print(path + ' exists')
        return
        
    os.makedirs(path)
    print(path + ' created')

def save_data(data):
    check_create(OUTPUT_PATH)
    now = str(int(time.time()))
    with open(OUTPUT_PATH + now + '.pickle', 'wb') as handle:
        pickle.dump(data, handle)

def balanced_valid_ixs(valid):
    crackle_ix = []
    no_crackle_ix = []
    
    for i in range(len(valid)):
        if valid[i]['label'].item() == 1:
            crackle_ix.append(i)
        else:
            no_crackle_ix.append(i)
    
    return crackle_ix + no_crackle_ix[:len(crackle_ix)]

def init_loaders():
    tfs = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomVerticalFlip(),
        transforms.RandomRotation(5),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])


    if SPLIT_MODE == 'auto':
        whole = datasets.ImageFolder('../acquisition/dataset_demo_diretor', transform=tfs)
        n_train = int(len(whole)*(1-VAL_SIZE))
        n_val = len(whole) - n_train
        train, valid = random_split(whole, [n_train, n_val])

    if SPLIT_MODE == 'manual':
        train = datasets.ImageFolder('../acquisition/dataset_demo_diretor/train', transform=tfs)
        valid = datasets.ImageFolder('../acquisition/dataset_demo_diretor/test', transform=tfs)
        
    trainloader = DataLoader(train, batch_size=BS, drop_last=False)

    validloader = DataLoader(valid, batch_size=BS, drop_last=False,
                            shuffle=False)

    return trainloader, validloader

def metrics(targets, y_pred):
    return torch.sum(targets == y_pred).item() / targets.numel(), confusion_matrix(targets.numpy()
                                                        , y_pred.numpy())
def train_model(model, criterion, optimizer, scheduler, num_epochs=25):
    since = time.time()
    upsample = nn.Upsample((224, 224))
    best_model_wts = copy.deepcopy(model.state_dict())
    best_acc = 0.0
    # data = {'train_loss': [], 'train_acc': [], 'train_cnf': [],
    #         'val_loss': [], 'val_acc': [], 'val_cnf': [],
    #         'params': {
    #             'LR_0': LR_0,
    #             'GAMMA': GAMMA,
    #             'N_EPOCHS': N_EPOCHS,
    #             'STEP_SIZE': STEP_SIZE,
    #             'MOMENTUM': MOMENTUM,
    #             'WD': WD,
    #             'CLASS_WEIGHTS': CLASS_WEIGHTS
    #              }
    #        }

    for epoch in range(num_epochs):
        print('Epoch {}/{}'.format(epoch, num_epochs - 1))
        print('-' * 10)

        # Each epoch has a training and validation phase
        for phase in ['train', 'val']:
            if phase == 'train':
                scheduler.step()
                model.train()  # Set model to training mode
            else:
                model.eval()   # Set model to evaluate mode

            running_loss = 0.0
            preds_acc = []
            labels_acc = []

            # Iterate over data.
            for i, batch in enumerate(dataloaders[phase]):
                inputs = batch[0]
                labels = batch[1]
                inputs = inputs.to(device, dtype=torch.float)
                inputs = upsample(inputs)
                labels = labels.to(device)

                # zero the parameter gradients
                optimizer.zero_grad()

                # forward
                # track history if only in train
                with torch.set_grad_enabled(phase == 'train'):
                    outputs = model(inputs)
                    _, preds = torch.max(outputs, 1)
                    loss = criterion(outputs, labels)

                    # backward + optimize only if in training phase
                    if phase == 'train':
                        loss.backward()
                        optimizer.step()

                # statisticsstatisticsstatistics
                running_loss += loss.item() * inputs.size(0)
                preds_acc.append(preds)
                labels_acc.append(labels)

            epoch_loss = running_loss / dataset_sizes[phase]
            epoch_acc, cnf_mat = metrics(torch.cat(labels_acc).cpu(), torch.cat(preds_acc).cpu())
            
            print('{} Loss: {:.4f} Acc: {:.4f}'.format(
                phase, epoch_loss, epoch_acc))

            print(cnf_mat)

            # deep copy the model
            if phase == 'val' and epoch_acc > best_acc:
                best_acc = epoch_acc
                best_model_wts = copy.deepcopy(model.state_dict())

        print()

    time_elapsed = time.time() - since
    print('Training complete in {:.0f}m {:.0f}s'.format(
        time_elapsed // 60, time_elapsed % 60))
    print('Best val Acc: {:4f}'.format(best_acc))

    # load best model weights
    model.load_state_dict(best_model_wts)
    return model

# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") #some arcane cuda magic on my pc and this breaks

if COLAB:
    device = torch.device("cuda:0")
    print('running on gpu! cuda:0')

else:
    device = torch.device("cpu")
    print('running on cpu!')

if SPLIT_MODE == 'manual': n_runs = 1 # if using a premade split, only run once
else: n_runs = N_SPLITS

for run in range(n_runs):

    trainloader, validloader = init_loaders()
    print(f'Run {run+1} out of {n_runs}')
    dataloaders = {'train': trainloader, 'val': validloader}
    dataset_sizes = {x: len(dataloaders[x])*BS for x in ['train', 'val']}

    model_ft = models.resnet18(pretrained=True)
    num_ftrs = model_ft.fc.in_features
    model_ft.fc = nn.Linear(num_ftrs, N_CLASSES)

    model_ft = model_ft.to(device)

    criterion = nn.CrossEntropyLoss()

    # Observe that all parameters are being optimized
    optimizer_ft = optim.SGD(model_ft.parameters(), lr=LR_0, momentum=MOMENTUM, weight_decay = WD)
#     optimizer_ft = optim.RMSprop(model_ft.parameters(), lr=LR_0, momentum=MOMENTUM, weight_decay = WD)
#     optimizer_ft = optim.Adam(model_ft.parameters(), lr=LR_0, weight_decay = WD)
    
    
    exp_lr_scheduler = lr_scheduler.StepLR(optimizer_ft, step_size=STEP_SIZE, gamma=GAMMA)
    model_ft = train_model(model_ft, criterion, optimizer_ft, exp_lr_scheduler,
                        num_epochs=N_EPOCHS)

    now = str(int(time.time()))
    torch.save(model_ft.state_dict(), MODEL_PATH + now + '.model')

running on gpu! cuda:0
Run 1 out of 1


Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /root/.cache/torch/checkpoints/resnet18-5c106cde.pth
100%|██████████| 46827520/46827520 [00:00<00:00, 107441494.86it/s]


Epoch 0/2
----------
train Loss: 0.6609 Acc: 0.7464
[[ 91   4  23   2   0]
 [  4  54   9   0   2]
 [ 26   2 118  10   1]
 [  6   0  18  44   0]
 [  6   1  10   0  58]]
val Loss: 0.0578 Acc: 0.9953
[[60  0  0  0  0]
 [ 0 31  0  0  0]
 [ 1  0 62  0  0]
 [ 0  0  0 32  0]
 [ 0  0  0  0 25]]

Epoch 1/2
----------
train Loss: 0.1442 Acc: 0.9673
[[116   0   4   0   0]
 [  0  69   0   0   0]
 [  8   0 147   0   2]
 [  0   0   1  67   0]
 [  0   0   1   0  74]]
val Loss: 0.0176 Acc: 1.0000
[[60  0  0  0  0]
 [ 0 31  0  0  0]
 [ 0  0 63  0  0]
 [ 0  0  0 32  0]
 [ 0  0  0  0 25]]

Epoch 2/2
----------
train Loss: 0.1242 Acc: 0.9816
[[115   0   5   0   0]
 [  0  69   0   0   0]
 [  1   0 154   2   0]
 [  0   0   0  68   0]
 [  0   0   1   0  74]]
val Loss: 0.0199 Acc: 1.0000
[[60  0  0  0  0]
 [ 0 31  0  0  0]
 [ 0  0 63  0  0]
 [ 0  0  0 32  0]
 [ 0  0  0  0 25]]

Training complete in 0m 32s
Best val Acc: 1.000000
